/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as MateriasPrimasRouteImport } from './routes/materias-primas'
import { Route as NovaAnaliseRouteImport } from './routes/nova-analise'
import { Route as AnaliseAnalysisIdRouteImport } from './routes/analise.$analysisId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasPrimasRoute = MateriasPrimasRouteImport.update({
  id: '/materias-primas',
  path: '/materias-primas',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaAnaliseRoute = NovaAnaliseRouteImport.update({
  id: '/nova-analise',
  path: '/nova-analise',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseAnalysisIdRoute = AnaliseAnalysisIdRouteImport.update({
  id: '/analise/$analysisId',
  path: '/analise/$analysisId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/materias-primas': typeof MateriasPrimasRoute
  '/nova-analise': typeof NovaAnaliseRoute
  '/analise/$analysisId': typeof AnaliseAnalysisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/materias-primas': typeof MateriasPrimasRoute
  '/nova-analise': typeof NovaAnaliseRoute
  '/analise/$analysisId': typeof AnaliseAnalysisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/materias-primas': typeof MateriasPrimasRoute
  '/nova-analise': typeof NovaAnaliseRoute
  '/analise/$analysisId': typeof AnaliseAnalysisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/materias-primas'
    | '/nova-analise'
    | '/analise/$analysisId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/materias-primas'
    | '/nova-analise'
    | '/analise/$analysisId'
  id:
    | '__root__'
    | '/'
    | '/entrar'
    | '/materias-primas'
    | '/nova-analise'
    | '/analise/$analysisId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntrarRoute: typeof EntrarRoute
  MateriasPrimasRoute: typeof MateriasPrimasRoute
  NovaAnaliseRoute: typeof NovaAnaliseRoute
  AnaliseAnalysisIdRoute: typeof AnaliseAnalysisIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias-primas': {
      id: '/materias-primas'
      path: '/materias-primas'
      fullPath: '/materias-primas'
      preLoaderRoute: typeof MateriasPrimasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-analise': {
      id: '/nova-analise'
      path: '/nova-analise'
      fullPath: '/nova-analise'
      preLoaderRoute: typeof NovaAnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise/$analysisId': {
      id: '/analise/$analysisId'
      path: '/analise/$analysisId'
      fullPath: '/analise/$analysisId'
      preLoaderRoute: typeof AnaliseAnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntrarRoute: EntrarRoute,
  MateriasPrimasRoute: MateriasPrimasRoute,
  NovaAnaliseRoute: NovaAnaliseRoute,
  AnaliseAnalysisIdRoute: AnaliseAnalysisIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
